version: '3.3'

services:
  web:
    build: .
    #command: "/bin/sh -c 'while true; do sleep 2h; done;'" #python manage.py runserver 0.0.0.0:8000
    command: gunicorn fs.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/bob/fs
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bob
      - POSTGRES_PASSWORD=bob12345
      - POSTGRES_DB=filesystem
    ports:
      - 5432:5432